add a link to failed DCO status to info about DCO
chef/dcob pull request #5
Opened 2016-10-04 05:45 UTC by robbkidd

Make a failed DCO status include a link to our DCO information in the chef/chef CONTRIBUTING doc. Is chef/chef a weird thing to link to from this habitat-sh project?

Also, bonus removal of trailing whitespace.

2016-10-04 09:35 UTC, thommay requested changes
Target URL should be a config option…

2016-10-04 09:47 UTC, robbkidd commented
![can do](https://cloud.githubusercontent.com/assets/517302/19069727/0f15d9e4-89f6-11e6-8b67-a6a6b942af3a.gif)

2016-10-04 20:08 UTC, robbkidd commented
This configurable DCO info link works when paired with #3's fixes to `default.toml` and plan.

2016-10-05 14:17 UTC, thommay approved these changes

2016-10-05 14:18 UTC, robbkidd commented
Rebased to master.

Hmm. The new Review system doesn't seem to like rebases.

![error](https://cloud.githubusercontent.com/assets/517302/19116882/fa5da76c-8ae4-11e6-9276-0f0ce52b5cd7.gif)

2016-10-05 14:18 UTC, merged